version: '3.1'

services:
    nginx:
        image: nginx
    apache:
        image: httpd
    json-server:
      image: clue/json-server
      volumes:
        - ./api_data/db.json:/data/db.json
      ports:
        - "8000:80"
    krakend:
        image: devopsfaith/krakend
        ports:
            - "80:8080"
        volumes:
            - ./krakend.json:/etc/krakend/krakend.json
        depends_on:
            - nginx
            - apache
            - json-server